# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hello. I'm Trevor Muraro."
email: 'trevormuraro@gmail.com'
description: "I'm an embedded and robotics engineer from Berkeley with experience in both software and hardware design.  I like exploring new fields and learning new skills."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TrevorMuraro.github.io/TrevorMuraro" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 'jamigibbs'
github_username: 'TrevorMuraro'
linkedin_username: 'trevor-muraro'
#medium_username: 'blog.jamigibbs.com'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
footer_text: '© 2018 Trevor Muraro'
admin_name: 'Trevor Muraro'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: false
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
